// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddStudentComponent: typeof import('./src/components/teacher/AddStudentComponent.vue')['default']
    CodeComponent: typeof import('./src/components/student/CodeComponent.vue')['default']
    ConsultComponent: typeof import('./src/components/teacher/ConsultComponent.vue')['default']
    CourseComponent: typeof import('./src/components/student/CourseComponent.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    Header: typeof import('./src/components/student/Header.vue')['default']
    HomeComponent: typeof import('./src/components/student/HomeComponent.vue')['default']
    MonacoEditor: typeof import('./src/components/student/monacoEditor.vue')['default']
    ProblemComponent: typeof import('./src/components/student/ProblemComponent.vue')['default']
    ReleaseComponent: typeof import('./src/components/teacher/ReleaseComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/teacher/sidebar.vue')['default']
    StudentInfoComponent: typeof import('./src/components/student/StudentInfoComponent.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
  }
}
